Repository Red-Hat-AI-Innovation-Team/sdg_hub, pull requests merged in 2025-10, with the labels that each got.

#452 Text parser doc
  docs/blocks/llm-blocks.md
Labels: documentation

#455 documentation for flow checkpointing
  docs/flows/overview.md
Labels: documentation

#269 Add integration test framework for notebook execution and enable in CI
  .github/workflows/integration-test.yml
  .github/workflows/test.yml
  .gitignore
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/knowledge_generation.ipynb
  pyproject.toml
  tests/integration/README.md
  tests/integration/__init__.py
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/README.md
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/__init__.py
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/conftest.py
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/test_functional.py
  tox.ini
Labels: documentation, testing, CI/CD

#456 Simplify flow metadata by removing unused parameter system
  examples/annotation/news_classification_flow.yaml
  src/sdg_hub/__init__.py
  src/sdg_hub/core/__init__.py
  src/sdg_hub/core/flow/__init__.py
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/flow/metadata.py
  src/sdg_hub/core/flow/registry.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enhanced_multi_summary_qa/detailed_summary/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enhanced_multi_summary_qa/doc_direct_qa/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enhanced_multi_summary_qa/extractive_summary/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enhanced_multi_summary_qa/key_facts/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/instructlab/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/flow.yaml
  src/sdg_hub/flows/text_analysis/structured_insights/flow.yaml
  tests/flow/test_base.py
  tests/flow/test_integration.py
  tests/flow/test_metadata.py
Labels: testing

#453 example for accessing flow info
  docs/flows/discovery.md
Labels: documentation

#447 feat(flow): add execution time estimation for flows
  docs/concepts.md
  docs/flows/overview.md
  docs/quick-start.md
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/utils/__init__.py
  src/sdg_hub/core/utils/flow_metrics.py
  src/sdg_hub/core/utils/time_estimator.py
  tests/flow/test_base.py
  tests/flow/test_time_estimation.py
  tests/utils/test_flow_metrics.py
Labels: documentation, testing

#460 fix integration tests to accommodate updated notebook
  .github/workflows/integration-test.yml
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/test_data/test_seed_data.jsonl
  tests/integration/knowledge_tuning/enhanced_summary_knowledge_tuning/test_functional.py
Labels: testing

#462 Remove deprecated components scheduled for next release
  CLAUDE.md
  src/sdg_hub/core/blocks/__init__.py
  src/sdg_hub/core/blocks/deprecated_blocks/__init__.py
  src/sdg_hub/core/blocks/deprecated_blocks/combine_columns.py
  src/sdg_hub/core/blocks/deprecated_blocks/duplicate_columns.py
  src/sdg_hub/core/blocks/deprecated_blocks/filter_by_value.py
  src/sdg_hub/core/blocks/deprecated_blocks/flatten_columns.py
  src/sdg_hub/core/blocks/deprecated_blocks/llmblock.py
  src/sdg_hub/core/blocks/deprecated_blocks/rename_columns.py
  src/sdg_hub/core/blocks/deprecated_blocks/sample_populator.py
  src/sdg_hub/core/blocks/deprecated_blocks/selector.py
  src/sdg_hub/core/blocks/deprecated_blocks/set_to_majority_value.py
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/flow/migration.py
  tests/blocks/deprecated/test_llmblock.py
  tests/blocks/transform/test_uniform_col_val_setter.py
  tests/blocks/utilblocks/test_combinecolumns.py
  tests/blocks/utilblocks/test_duplicatecolumnsblock.py
  tests/blocks/utilblocks/test_flattenblock.py
  tests/blocks/utilblocks/test_renameblock.py
  tests/blocks/utilblocks/test_samplepopulatorblock.py
  tests/blocks/utilblocks/test_selectorblock.py
  tests/blocks/utilblocks/test_settomajority.py
  tests/flow/test_migration.py
Labels: documentation, testing, run-integration-tests
