Repository Red-Hat-AI-Innovation-Team/sdg_hub, pull requests merged in 2025-09, with the labels that each got.

#332 knowledge tuning using Enhanced Summarization
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/.env
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/README.md
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/knowledge_generation.ipynb
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/knowledge_mixing.ipynb
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/knowledge_mixing_utils.py
  examples/knowledge_tuning/enhanced_summary_knowledge_tuning/requirements.txt
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/__init__.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/detailed_summary/__init__.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/detailed_summary/detailed_summary.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/detailed_summary/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/evaluate_faithfulness.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/evaluate_question.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/evaluate_relevancy.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/extractive_summary/__init__.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/extractive_summary/extractive_summary.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/extractive_summary/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/generate_answers.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/generate_question_list.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/key_facts/__init__.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/key_facts/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/enchance_multi_summary_qa/key_facts/key_facts_summary.yaml
Labels: documentation, ci-failure

#383 Feat/retain all message contents -- support GPT-OSS
  src/sdg_hub/core/blocks/llm/client_manager.py
  src/sdg_hub/core/blocks/llm/llm_chat_block.py
  src/sdg_hub/core/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_llm_chat_block.py
  tests/blocks/llm/test_llm_chat_with_parsing_retry_block.py
  tests/blocks/llm/test_textparserblock.py
Labels: testing

#410 Feat/add flow metrics
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/utils/flow_metrics.py
Labels: ci-failure

#416 Improve entity extraction with structured JSON output
  examples/text_analysis/README.md
  examples/text_analysis/extract_stock_tickers.yaml
  examples/text_analysis/structured_insights_demo.ipynb
  src/sdg_hub/flows/text_analysis/structured_insights/extract_entities.yaml
  src/sdg_hub/flows/text_analysis/structured_insights/flow.yaml
Labels: documentation

#415 Fix/support str text parser
  src/sdg_hub/core/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_textparserblock.py
Labels: testing

#413 Fix/override kwargs base block
  src/sdg_hub/core/blocks/base.py
  src/sdg_hub/core/blocks/evaluation/evaluate_faithfulness_block.py
  src/sdg_hub/core/blocks/evaluation/evaluate_relevancy_block.py
  src/sdg_hub/core/blocks/evaluation/verify_question_block.py
  src/sdg_hub/core/blocks/llm/__init__.py
  src/sdg_hub/core/blocks/llm/client_manager.py
  src/sdg_hub/core/blocks/llm/config.py
  src/sdg_hub/core/blocks/llm/llm_chat_block.py
  src/sdg_hub/core/blocks/llm/llm_chat_with_parsing_retry_block.py
  src/sdg_hub/core/blocks/llm/text_parser_block.py
  src/sdg_hub/core/flow/base.py
  tests/blocks/evaluation/test_verify_question_block.py
  tests/blocks/llm/test_llm_chat_block.py
  tests/blocks/llm/test_llm_chat_with_parsing_retry_block.py
  tests/blocks/llm/test_textparserblock.py
  tests/blocks/test_base_block.py
  tests/flow/test_base.py
Labels: testing, ci-failure

#421 Add a Japanese knowledge SDG flow
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/README.md
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/__init__.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/atomic_facts_ja.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/detailed_summary_ja.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/extractive_summary_ja.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/flow.yaml
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/multilingual/japanese/generate_questions_responses_ja.yaml
Labels: documentation

#450 Remove Evaluation blocks
  docs/README.md
  docs/_sidebar.md
  docs/blocks/evaluation-blocks.md
  docs/blocks/filtering-blocks.md
  docs/blocks/llm-blocks.md
  docs/blocks/overview.md
  docs/blocks/transform-blocks.md
  docs/concepts.md
  docs/development.md
  docs/flows/overview.md
  src/sdg_hub/core/blocks/__init__.py
  src/sdg_hub/core/blocks/evaluation/__init__.py
  src/sdg_hub/core/blocks/evaluation/evaluate_faithfulness_block.py
  src/sdg_hub/core/blocks/evaluation/evaluate_relevancy_block.py
  src/sdg_hub/core/blocks/evaluation/verify_question_block.py
  tests/blocks/evaluation/__init__.py
  tests/blocks/evaluation/test_evaluate_faithfulness_block.py
  tests/blocks/evaluation/test_evaluate_relevancy_block.py
  tests/blocks/evaluation/test_verify_question_block.py
  tests/blocks/testdata/test_evaluate_faithfulness.yaml
  tests/blocks/testdata/test_evaluate_relevancy.yaml
  tests/blocks/testdata/test_verify_question.yaml
Labels: documentation, testing
