Repository Red-Hat-AI-Innovation-Team/sdg_hub, pull requests merged in 2025-08, with the labels that each got.

#301 Enhance README and CLAUDE.md with improved messaging and structure
  CLAUDE.md
  README.md
Labels: documentation

#328 Update README.md to use uv natively for all installation commands
  README.md
Labels: documentation

#305 Fix FlowParameter attribute error in print_info method
  src/sdg_hub/core/flow/base.py
Labels: ci-failure, review

#314 Feature/flow id system
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/flow/metadata.py
  src/sdg_hub/core/flow/migration.py
  src/sdg_hub/core/flow/registry.py
  src/sdg_hub/core/flow/validation.py
  src/sdg_hub/core/utils/__init__.py
  src/sdg_hub/core/utils/flow_id_words.yaml
  src/sdg_hub/core/utils/flow_identifier.py
  src/sdg_hub/core/utils/yaml_utils.py
  src/sdg_hub/flows/qa_generation/document_grounded_qa/multi_summary_qa/instructlab/flow.yaml
  tests/flow/test_integration.py
  tests/flow/test_metadata.py
  tests/flow/test_migration.py
  tests/flow/test_registry.py
Labels: testing

#342 Add Flow-level checkpointing with sample-level tracking
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/flow/checkpointer.py
  src/sdg_hub/core/utils/datautils.py
  tests/flow/test_base.py
  tests/flow/test_checkpointer.py
  tests/utils/test_error_handling.py
Labels: testing

#348 Add comprehensive tests for LLMChatWithParsingRetryBlock
  src/sdg_hub/core/blocks/llm/__init__.py
  src/sdg_hub/core/blocks/llm/llm_chat_with_parsing_retry_block.py
  tests/blocks/llm/test_llm_chat_with_parsing_retry_block.py
Labels: testing

#351 Add expand_lists parameter to TextParserBlock
  src/sdg_hub/core/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_textparserblock.py
Labels: testing

#352 Update README with flow ID system documentation
  README.md
Labels: documentation

#367 Fix #363 timeout not respected
  src/sdg_hub/core/blocks/llm/config.py
  tests/blocks/llm/test_llm_chat_block.py
Labels: testing

#370 Add dataset schema discovery functionality
  README.md
  src/sdg_hub/core/flow/base.py
  tests/flow/test_dataset_requirements.py
Labels: documentation, testing

#371 Fix retry counting for expand_lists=False in LLMChatWithParsingRetryBlock
  src/sdg_hub/core/blocks/llm/llm_chat_with_parsing_retry_block.py
  src/sdg_hub/core/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_llm_chat_with_parsing_retry_block.py
Labels: testing

#361 fix(flows): adding deduplicate row validation
  src/sdg_hub/core/flow/base.py
  src/sdg_hub/core/utils/datautils.py
  tests/utils/test_datautils.py
Labels: testing

#372 Feat/max concurrency
  docs/blocks/llm-blocks.md
  docs/concepts.md
  docs/flows/overview.md
  src/sdg_hub/core/blocks/deprecated_blocks/selector.py
  src/sdg_hub/core/blocks/llm/client_manager.py
  src/sdg_hub/core/blocks/llm/llm_chat_block.py
  src/sdg_hub/core/blocks/transform/index_based_mapper.py
  src/sdg_hub/core/flow/base.py
  tests/flow/test_base.py
Labels: documentation, testing, ci-failure
