Repository Red-Hat-AI-Innovation-Team/sdg_hub, pull requests merged in 2025-07, with the labels that each got.

#232 Add custom validation hook to BaseBlock
  src/sdg_hub/blocks/base.py
  tests/blocks/test_base_block.py
Labels: testing

#235 Add dictionary support to BaseBlock column specifications
  src/sdg_hub/blocks/base.py
  tests/blocks/test_base_block.py
Labels: testing

#214 Updating knowledge utils, and notebooks, and adding readme for knowledge and instructlab knowledge
  examples/knowledge_tuning/README.md
  examples/knowledge_tuning/instructlab/README.md
  examples/knowledge_tuning/instructlab/knowledge_generation_and_mixing.ipynb
  examples/knowledge_tuning/knowledge_utils.py
  src/sdg_hub/flows/generation/knowledge/synth_knowledge1.5.yaml
Labels: documentation, refactor

#240 Refactor TextParserBlock to extend BaseBlock and enhance validation
  src/sdg_hub/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_textparserblock.py
Labels: testing

#241 Enhance BlockRegistry with metadata, auto-discovery, and better error handling
  src/sdg_hub/blocks/filtering/filter_by_value.py
  src/sdg_hub/blocks/llm/llm_chat_block.py
  src/sdg_hub/blocks/llm/prompt_builder_block.py
  src/sdg_hub/blocks/llm/text_parser_block.py
  src/sdg_hub/blocks/registry.py
  tests/blocks/llm/test_llm_chat_block.py
  tests/blocks/test_registry.py
Labels: testing

#244 Add get_config() method to BaseBlock for better serialization support
  src/sdg_hub/blocks/base.py
  tests/blocks/test_base_block.py
Labels: testing

#253 Refactor PromptBuilderBlock to use new YAML message format and Pydantic models
  src/sdg_hub/blocks/llm/prompt_builder_block.py
  tests/blocks/llm/test_promptbuilderblock.py
  tests/blocks/testdata/test_prompt_format_config.yaml
  tests/blocks/testdata/test_prompt_format_no_system.yaml
  tests/blocks/testdata/test_prompt_format_strict.yaml
  tests/blocks/testdata/test_prompt_invalid_final_role.yaml
  tests/blocks/testdata/test_prompt_no_user_messages.yaml
Labels: testing

#243 Refactor transform blocks to use BaseBlock and dedicated module
  src/sdg_hub/blocks/transform/__init__.py
  src/sdg_hub/blocks/transform/flatten_columns.py
  src/sdg_hub/blocks/transform/index_based_mapper.py
  src/sdg_hub/blocks/transform/set_majority_value.py
  tests/blocks/transform/test_flatten_columns.py
  tests/blocks/transform/test_index_based_mapper.py
  tests/blocks/transform/test_set_majority_value.py
Labels: testing

#262 Implement backwards compatibility for block refactoring
  src/sdg_hub/blocks/__init__.py
  src/sdg_hub/blocks/deprecated_blocks/__init__.py
  src/sdg_hub/blocks/deprecated_blocks/combine_columns.py
  src/sdg_hub/blocks/deprecated_blocks/duplicate_columns.py
  src/sdg_hub/blocks/deprecated_blocks/filter_by_value.py
  src/sdg_hub/blocks/deprecated_blocks/flatten_columns.py
  src/sdg_hub/blocks/deprecated_blocks/rename_columns.py
  src/sdg_hub/blocks/deprecated_blocks/sample_populator.py
  src/sdg_hub/blocks/deprecated_blocks/selector.py
  src/sdg_hub/blocks/deprecated_blocks/set_to_majority_value.py
  src/sdg_hub/blocks/filtering/__init__.py
  src/sdg_hub/blocks/filtering/column_value_filter.py
  src/sdg_hub/blocks/transform/__init__.py
  src/sdg_hub/blocks/transform/duplicate_columns.py
  src/sdg_hub/blocks/transform/melt_columns.py
  src/sdg_hub/blocks/transform/rename_columns.py
  src/sdg_hub/blocks/transform/set_majority_value.py
  src/sdg_hub/blocks/transform/text_concat.py
  src/sdg_hub/blocks/utilblocks.py
  tests/blocks/filtering/test_columnvaluefilter.py
  tests/blocks/transform/test_melt_columns.py
  tests/blocks/transform/test_text_concat.py
  tests/blocks/utilblocks/test_combinecolumns.py
  tests/blocks/utilblocks/test_duplicatecolumnsblock.py
  tests/blocks/utilblocks/test_flattenblock.py
  tests/blocks/utilblocks/test_renameblock.py
  tests/blocks/utilblocks/test_samplepopulatorblock.py
  tests/blocks/utilblocks/test_selectorblock.py
  tests/blocks/utilblocks/test_settomajority.py
Labels: testing

#265 Fix: Add support for n parameter (multiple completions) in LLM blocks
  src/sdg_hub/blocks/llm/client_manager.py
  src/sdg_hub/blocks/llm/llm_chat_block.py
  tests/blocks/llm/test_llm_chat_block.py
Labels: testing

#258 Add redesigned Flow system with enhanced discovery and validation
  src/sdg_hub/blocks/deprecated_blocks/combine_columns.py
  src/sdg_hub/blocks/deprecated_blocks/duplicate_columns.py
  src/sdg_hub/blocks/deprecated_blocks/filter_by_value.py
  src/sdg_hub/blocks/deprecated_blocks/flatten_columns.py
  src/sdg_hub/blocks/deprecated_blocks/llmblock.py
  src/sdg_hub/blocks/deprecated_blocks/rename_columns.py
  src/sdg_hub/blocks/deprecated_blocks/sample_populator.py
  src/sdg_hub/blocks/deprecated_blocks/selector.py
  src/sdg_hub/blocks/deprecated_blocks/set_to_majority_value.py
  src/sdg_hub/flow.py
  src/sdg_hub/flow/__init__.py
  src/sdg_hub/flow/base.py
  src/sdg_hub/flow/metadata.py
  src/sdg_hub/flow/migration.py
  src/sdg_hub/flow/registry.py
  src/sdg_hub/flow/validation.py
  test_migration.py
  tests/blocks/deprecated/test_llmblock.py
  tests/blocks/test_registry.py
  tests/flow/__init__.py
  tests/flow/conftest.py
  tests/flow/test_base.py
  tests/flow/test_integration.py
  tests/flow/test_metadata.py
  tests/flow/test_migration.py
  tests/flow/test_registry.py
  tests/flow/test_validation.py
  tests/flows/test_flow.py
  tests/flows/test_flow_column_validation.py
  tests/flows/test_flow_path.py
  tests/flows/test_flow_validation.py
  tests/flows/testdata/test_config_1.yaml
  tests/flows/testdata/test_flow_1.yaml
  tests/flows/testdata/test_flow_2.yaml
Labels: testing, ci-failure

#281 Fix TextParserBlock to handle list inputs from LLMChatBlock when n>1
  src/sdg_hub/blocks/llm/text_parser_block.py
  tests/blocks/llm/test_textparserblock.py
Labels: testing

#273 Add EvaluateFaithfulnessBlock composite evaluation block
  src/sdg_hub/blocks/__init__.py
  src/sdg_hub/blocks/evaluation/__init__.py
  src/sdg_hub/blocks/evaluation/evaluate_faithfulness_block.py
  tests/blocks/evaluation/__init__.py
  tests/blocks/evaluation/test_evaluate_faithfulness_block.py
  tests/blocks/testdata/test_evaluate_faithfulness.yaml
Labels: testing

#285 Add EvaluateRelevancyBlock composite evaluation block
  src/sdg_hub/blocks/__init__.py
  src/sdg_hub/blocks/evaluation/__init__.py
  src/sdg_hub/blocks/evaluation/evaluate_relevancy_block.py
  tests/blocks/evaluation/test_evaluate_relevancy_block.py
  tests/blocks/testdata/test_evaluate_relevancy.yaml
Labels: testing
